language: python

env:
  - TOXENV=py27
  - TOXENV=py27-configparser
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy

install:
  - git config --global user.email "bumpversion-test-git@travis.ci"
  - git config --global user.name "Testing Git on Travis CI"
  - git --version
  - git config --list
  - echo -e '[ui]\nusername = Testing Mercurial on Travis CI <bumpversion-test-hg@travis.ci>' > ~/.hgrc
  - hg --version
  - pip install --upgrade pytest tox

script:
  - tox

