
version: '{build}'

build: off

environment:
  matrix:
    - PYTHON: "C:/Python27"
      TOXENV: "py27"

    - PYTHON: "C:/Python27-x64"
      TOXENV: "py27"

    - PYTHON: "C:/Python27"
      TOXENV: "py27-configparser"

    - PYTHON: "C:/Python27-x64"
      TOXENV: "py27-configparser"

    - PYTHON: "C:/Python33"
      TOXENV: "py33"

    - PYTHON: "C:/Python33-x64"
      TOXENV: "py33"

    - PYTHON: "C:/Python34"
      TOXENV: "py34"

    - PYTHON: "C:/Python34-x64"
      TOXENV: "py34"

init:
  - "ECHO %TOXENV%"
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install virtualenv"
  - "%PYTHON%/Scripts/pip.exe install tox"
  - "%PYTHON%/Scripts/pip.exe install mercurial"
  - "%PYTHON%/Scripts/pip.exe install -e ."

test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/virtualenv.exe --version"
  - "%PYTHON%/Scripts/tox.exe --version"
  - "%PYTHON%/Scripts/tox.exe"
